export { default as Destiantions} from "./destination"
export {default as Seats} from "./Seats"
export {default as SeatsBook} from "./SeatsBook"
export {default as Popups} from "./popup"
export {default as Accounts} from "./Accounts"
export {default as Header} from "./header"